feature/De 89 cadastrar proposito
desenvolvendo-me/developer-evolution pull request #10
Opened 2023-06-09 12:35 UTC by ansulima

Foi criado models 
Foi feito testes nos models
Foram feitas correções nos models e migrates

2023-07-16 21:22 UTC, gugovisk commented on spec/models/purpose_spec.rb
Reescrever os testes do model usando Shoulda Matchers: https://matchers.shoulda.io/. Temos alguns exemplos disso também na feature Cadastrar Experiência na release/v0.2, que poderão ser bem úteis para aproveitar.

2023-07-16 21:22 UTC, gugovisk commented on spec/requests/purposes_spec.rb
Não foi solicitado teste pra requests.

2023-07-16 21:22 UTC, gugovisk commented on spec/routing/purposes_routing_spec.rb
Não foi solicitado teste pra routing.

2023-07-16 21:22 UTC, gugovisk commented on spec/views/purposes/edit.html.erb_spec.rb
Não foi solicitado teste pra views.

2023-07-16 21:22 UTC, gugovisk commented on spec/views/purposes/index.html.erb_spec.rb
Não foi solicitado teste pra views.

2023-07-16 21:22 UTC, gugovisk commented on spec/views/purposes/new.html.erb_spec.rb
Não foi solicitado teste pra views.

2023-07-16 21:22 UTC, gugovisk commented on spec/views/purposes/show.html.erb_spec.rb
Não foi solicitado teste pra views.

2023-07-17 16:13 UTC, PhilipeeX commented on app/helpers/purposes_helper.rb
> +module PurposesHelper
yagni: excluir arquivos nao utilizados

2023-07-17 16:13 UTC, PhilipeeX commented on app/views/purposes/edit.html.erb
> +  <%= link_to "Show this purpose", @purpose %> |
usar i18n

2023-07-17 16:13 UTC, PhilipeeX commented on spec/helpers/purposes_helper_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
yagni: excluir arquivos nao utilizados

2023-07-20 19:45 UTC, marcodotcastro requested changes
Ficou faltando mais relacionamento entre entidades para permitir o cadastro corretamente

2023-07-21 19:34 UTC, marcodotcastro commented on app/views/purposes/_form.html.erb
> +    <%= form.select :question, options_for_select(["Por que quer estudar programação?",
Essas informações devem ficar no model

2023-07-21 19:34 UTC, marcodotcastro commented on app/views/purposes/_form.html.erb
> +    <%= form.label :question, t('.question'), style: "display: block" %>
Essas informações devem ficar no model

2023-07-21 19:35 UTC, marcodotcastro commented on app/models/purpose.rb
> +  # validates :version, :time, :type_question, :question, :answer, presence: true
A estrutura do purpose está imcompleta para receber as informações

2023-07-21 19:36 UTC, marcodotcastro requested changes
Verifique os comentários e realize as alterações.

2023-07-21 23:17 UTC, ansulima commented on app/views/purposes/_form.html.erb
> +    <%= form.label :question, t('.question'), style: "display: block" %>
Ajuste feito! favor conferir!

2023-07-22 00:16 UTC, ansulima commented on app/models/purpose.rb
> +  # validates :version, :time, :type_question, :question, :answer, presence: true
Ajuste feito, favor conferir!

2023-07-22 00:17 UTC, ansulima commented on app/views/purposes/_form.html.erb
> +    <%= form.select :question, options_for_select(["Por que quer estudar programação?",
Ajuste feitos, favor conferir!

2023-07-29 23:11 UTC, PhilipeeX requested changes

2023-07-29 23:11 UTC, PhilipeeX commented on spec/views/purposes/edit.html.erb_spec.rb
ñ precisa dos testes de view

2023-07-31 18:50 UTC, marcodotcastro commented on app/models/purpose.rb
> +  # validates :version, :time, :type_question, :question, :answer, presence: true
Remover esse comentário

2023-07-31 18:51 UTC, marcodotcastro commented on app/helpers/application_helper.rb
Não deletar esse arquivo

2023-07-31 19:04 UTC, ansulima commented on app/helpers/application_helper.rb
Arquivo restaurado

2023-07-31 19:04 UTC, ansulima commented on app/models/purpose.rb
> +  # validates :version, :time, :type_question, :question, :answer, presence: true
Comentário removido

2023-07-31 19:57 UTC, marcodotcastro requested changes

2023-07-31 19:57 UTC, marcodotcastro commented on spec/routing/purposes_routing_spec.rb
Não foi solicitado test de routing

2023-08-03 19:36 UTC, closed without merging