Feature/22 cadastrar meta
desenvolvendo-me/developer-evolution pull request #59
Opened 2023-07-27 18:57 UTC by gudiao21

2023-07-27 19:23 UTC, marcodotcastro requested changes

2023-07-27 19:23 UTC, marcodotcastro commented on app/models/goal_question.rb
> +  belongs_to :goal
Faltando os enuns type_question e description

2023-08-03 19:44 UTC, marcodotcastro commented on app/controllers/goals_controller.rb
> +    #@goal.goal_questions.destroy_all
Remover código comentado

2023-08-03 19:52 UTC, marcodotcastro commented on config/routes.rb
> +  end
Remover esse código

2023-08-07 19:37 UTC, gudiao21 commented on app/controllers/goals_controller.rb
> +    #@goal.goal_questions.destroy_all
comentário removido.

2023-08-07 19:38 UTC, gudiao21 commented on config/routes.rb
> +  end
Respectivo código removido

2023-08-15 01:54 UTC, gudiao21 commented on app/models/goal_question.rb
> +  belongs_to :goal
Type_question e description adicionados.

2023-08-17 18:38 UTC, marcodotcastro approved these changes

2023-08-17 18:38 UTC, merged